//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTO()
        {
            this.VIAJES = new HashSet<VIAJE>();
            this.TURNOS = new HashSet<TURNO>();
        }
    
        public int ID_AUTO { get; set; }
        public int MARCA_ID { get; set; }
        public string MODELO { get; set; }
        public string PATENTE { get; set; }
        public string LICENCIA { get; set; }
        public string RODADO { get; set; }
        public bool HABILITADO { get; set; }
        public int CHOFER_ID { get; set; }
    
        public virtual CHOFERE CHOFERE { get; set; }
        public virtual MARCA MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJE> VIAJES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TURNO> TURNOS { get; set; }
    }
}
