//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHOFERE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHOFERE()
        {
            this.AUTOS = new HashSet<AUTO>();
            this.RENDICIONES = new HashSet<RENDICIONE>();
            this.VIAJES = new HashSet<VIAJE>();
        }
    
        public int ID_CHOFER { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public decimal DNI { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public string MAIL { get; set; }
        public System.DateTime FECHA_NAC { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public bool HABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTO> AUTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENDICIONE> RENDICIONES { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJE> VIAJES { get; set; }
    }
}
