//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberFrba
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GD1C2017Entities : DbContext
    {
        public GD1C2017Entities()
            : base("name=GD1C2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTO> AUTOS { get; set; }
        public virtual DbSet<CHOFERE> CHOFERES { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<FACTURA> FACTURAS { get; set; }
        public virtual DbSet<FUNCIONALIDADE> FUNCIONALIDADES { get; set; }
        public virtual DbSet<MARCA> MARCAS { get; set; }
        public virtual DbSet<RENDICIONE> RENDICIONES { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<TURNO> TURNOS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<VIAJE> VIAJES { get; set; }
    
        public virtual int insertTestTable(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertTestTable", nombreParameter);
        }
    
        public virtual ObjectResult<choferesMayorRecaudacionSP_Result> choferesMayorRecaudacionSP(Nullable<int> anio, Nullable<int> inicio, Nullable<int> fin)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(int));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<choferesMayorRecaudacionSP_Result>("choferesMayorRecaudacionSP", anioParameter, inicioParameter, finParameter);
        }
    
        public virtual ObjectResult<choferesViajeMasLargoSP_Result> choferesViajeMasLargoSP(Nullable<int> anio, Nullable<int> inicio, Nullable<int> fin)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(int));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<choferesViajeMasLargoSP_Result>("choferesViajeMasLargoSP", anioParameter, inicioParameter, finParameter);
        }
    
        public virtual ObjectResult<clientesMayorConsumoSP_Result> clientesMayorConsumoSP(Nullable<int> anio, Nullable<int> inicio, Nullable<int> fin)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(int));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<clientesMayorConsumoSP_Result>("clientesMayorConsumoSP", anioParameter, inicioParameter, finParameter);
        }
    
        public virtual ObjectResult<clientesMismoAutomovilMasFrecuenciaSP_Result> clientesMismoAutomovilMasFrecuenciaSP(Nullable<int> anio, Nullable<int> inicio, Nullable<int> fin)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(int));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<clientesMismoAutomovilMasFrecuenciaSP_Result>("clientesMismoAutomovilMasFrecuenciaSP", anioParameter, inicioParameter, finParameter);
        }
    }
}
