//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberFrba
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GD1C2017Entities : DbContext
    {
        public GD1C2017Entities()
            : base("name=GD1C2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTO> AUTOS { get; set; }
        public virtual DbSet<CHOFERE> CHOFERES { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<FACTURA> FACTURAS { get; set; }
        public virtual DbSet<FUNCIONALIDADE> FUNCIONALIDADES { get; set; }
        public virtual DbSet<MARCA> MARCAS { get; set; }
        public virtual DbSet<RENDICIONE> RENDICIONES { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<TURNO> TURNOS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<VIAJE> VIAJES { get; set; }
    
        public virtual ObjectResult<choferesMayorRecaudacionSP_Result1> choferesMayorRecaudacionSP(Nullable<int> anio, Nullable<int> inicio, Nullable<int> fin)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(int));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<choferesMayorRecaudacionSP_Result1>("choferesMayorRecaudacionSP", anioParameter, inicioParameter, finParameter);
        }
    
        public virtual ObjectResult<choferesViajeMasLargoSP_Result1> choferesViajeMasLargoSP(Nullable<int> anio, Nullable<int> inicio, Nullable<int> fin)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(int));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<choferesViajeMasLargoSP_Result1>("choferesViajeMasLargoSP", anioParameter, inicioParameter, finParameter);
        }
    
        public virtual ObjectResult<clientesMayorConsumoSP_Result1> clientesMayorConsumoSP(Nullable<int> anio, Nullable<int> inicio, Nullable<int> fin)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(int));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<clientesMayorConsumoSP_Result1>("clientesMayorConsumoSP", anioParameter, inicioParameter, finParameter);
        }
    
        public virtual ObjectResult<clientesMismoAutomovilMasFrecuenciaSP_Result1> clientesMismoAutomovilMasFrecuenciaSP(Nullable<int> anio, Nullable<int> inicio, Nullable<int> fin)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(int));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<clientesMismoAutomovilMasFrecuenciaSP_Result1>("clientesMismoAutomovilMasFrecuenciaSP", anioParameter, inicioParameter, finParameter);
        }
    }
}
