//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENDICIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENDICIONE()
        {
            this.VIAJES = new HashSet<VIAJE>();
        }
    
        public int ID_RENDICION { get; set; }
        public int TURNO_ID { get; set; }
        public decimal NUMERO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal IMPORTE { get; set; }
        public int CHOFER_ID { get; set; }
    
        public virtual CHOFERE CHOFERE { get; set; }
        public virtual TURNO TURNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJE> VIAJES { get; set; }
    }
}
