//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENDICIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENDICIONE()
        {
            this.VIAJES = new HashSet<VIAJE>();
        }
    
        public int ID_RENDICION { get; set; }
        public int TURNO_ID { get; set; }
        public decimal NUMERO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal IMPORTE { get; set; }
        public int CHOFER_ID { get; set; }
    
        public virtual CHOFERE CHOFERE { get; set; }
        public virtual TURNO TURNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJE> VIAJES { get; set; }
    }
}
