//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TURNO()
        {
            this.RENDICIONES = new HashSet<RENDICIONE>();
            this.VIAJES = new HashSet<VIAJE>();
            this.AUTOS = new HashSet<AUTO>();
        }
    
        public int ID_TURNO { get; set; }
        public decimal HORA_INICIO { get; set; }
        public decimal HORA_FIN { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal VALOR_KM { get; set; }
        public decimal PRECIO_BASE { get; set; }
        public bool HABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENDICIONE> RENDICIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJE> VIAJES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTO> AUTOS { get; set; }
    }
}
