//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberFrba
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJE
    {
        public int ID_VIAJE { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public decimal CANTIDAD_KM { get; set; }
        public int CHOFER_ID { get; set; }
        public int CLIENTE_ID { get; set; }
        public int AUTO_ID { get; set; }
        public int TURNO_ID { get; set; }
        public Nullable<int> RENDICION_ID { get; set; }
        public Nullable<int> FACTURA_ID { get; set; }
    
        public virtual AUTO AUTO { get; set; }
        public virtual CHOFERE CHOFERE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FACTURA FACTURA { get; set; }
        public virtual RENDICIONE RENDICIONE { get; set; }
        public virtual TURNO TURNO { get; set; }
    }
}
